### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by leotrs** [scikit-learn-contrib/metric-learn#251]
In [this](http://contrib.scikit-learn.org/metric-learn/weakly_supervised.html) documentation page, in the following paragraph

> The most intuitive way to represent tuples is to provide the algorithm with a 3D array-like of tuples of shape (n_tuples, t, n_features), where n_tuples is the number of tuples, tuple_size is the number of elements in a tuple (2 for pairs, 3 for triplets for instance), and n_features is the number of features of each point.

`t` should be `tuple_size` (or vice versa).

**Comment by wdevazelhes** [comment]
Hi @leotrs, that's right, thanks for pointing that out! Do you want to open a PR to fix it ?
