### ISSUE TITLE
[DOC] docs break with new sphinx

### ISSUE THREAD

**Issue by wdevazelhes** [scikit-learn-contrib/metric-learn#262]
See comment https://github.com/scikit-learn-contrib/metric-learn/issues/258#issuecomment-553482800. 

When building with the new sphinx version (2.1.1), references does not display prettily, though it works with some previous versions like 1.8, we should either make it work with the new version (preferably I guess), or add in the documentation which version to use

**Comment by terrytangyuan** [comment]
I agree that making it work with the new version would be preferred since there is a major upgrade of sphinx.

**Comment by bellet** [comment]
Fixed in #265
