### ISSUE TITLE
Question: Re: Feature selection

### ISSUE THREAD

**Issue by ttumkaya** [scikit-learn-contrib/metric-learn#285]
Hi,

Thank you for making this fantastic library available!

I have been using it to reduce dimensionality of my dataset prior to machine learning applications. While deciding how many features I must keep, I tried to calculate a Variable Importance Measure or Explained Variance measure, but it wasn't easy. Coefficients or eigenvalues are not readily returned by the functions.

What do you think is the most convenient way of doing this in a way that could be applied all the algorithms here?

Thanks,
Tayfun

**Comment by bellet** [comment]
Hi @ttumkaya, sorry for the late reply!

Using something like explained variance (as often done with PCA) does not seem so relevant as the metric is typically trained in a discriminative fashion.

The only generic way of choosing the dimension of transformed space that I can think of is cross-validation performance. If you are in the weakly supervised setting and only have tuples (say, positive/negative pairs), you can look for instance at the accuracy or AUC of predicting the label of pairs. If you have labels, you could use some classification measure (eg., k-NN accuracy on the transformed data).

Hope this helps

Of course this assumes you have a way to measure the usefulness of the representation in an "extrinsic" way.

**Comment by ttumkaya** [comment]
Hi @bellet,

Thanks so much for your reply! CV performance is what I ended up doing as well, glad to hear a confirmation from you.

Thanks,
Tayfun
