### ISSUE TITLE
[DOC] Solve links in docs

### ISSUE THREAD

**Issue by wdevazelhes** [scikit-learn-contrib/metric-learn#296]
We should solve the links to algorithms in the docs, they don't work since `` :ref:`modindex` `` was removed (see https://github.com/scikit-learn-contrib/metric-learn/pull/274#discussion_r367083294), so we need to find a solution that would solve both pbs (the missing page if there is `` :ref:`modindex` `` and the non-working links if there is not)

**Comment by wdevazelhes** [comment]
I noticed that if we keep the code as is now (i.e. with the fix from #274), but using sphinx 1.8.3 instead of the last version (3.1.1), it works

**Comment by bellet** [comment]
Did you try this?
https://stackoverflow.com/questions/55051112/why-is-sphinx-automodule-not-showing-any-module-members

**Comment by wdevazelhes** [comment]
Thanks for the link, in fact, I just retried with the new sphinx version (without this modification), upgrading it from the 1.8.3 to 3.1.1 using `pip install sphinx --upgrade` and this time it worked as expected, so I guess I had done something wrong in the installation the first time...

**Comment by bellet** [comment]
OK so I guess it is all good!
