### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by terrytangyuan** [scikit-learn-contrib/metric-learn#325]
See context in https://github.com/scikit-learn-contrib/metric-learn/pull/322#issuecomment-919196067.

**Comment by bellet** [comment]
I guess one needs to adapt this file: https://github.com/scikit-learn-contrib/metric-learn/blob/master/.travis.yml
I am not sure whether something needs to be done to get report summaries in the PR pages though

(BTW I don't think I'll have time to take care of this myself anytime soon)

**Comment by terrytangyuan** [comment]
I can help with this when I get a chance but anyone should feel free to work on it before I get to it.
